language: node_js
node_js:
- '7'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "pEtyYIuzOFbCjTeTQ3SyHLWzaMzZYTOyS6wr7YBV7tV91FF3hZsjjMAnSWUiAsd7il62Yxd7ZZl6MkAFgViIxx7noWeU92Jf62Wr7wvCHEGYd6dc/Nux2HvZrYH5o2bLTRuCSnqQ/EpETjqs2TiEkGcigQlDArf/YuT7ytzBbsDvAqOsX3frvKyg9MIDeH/4iVb6fGM5LyPpwSiG6XQDLaXCfuyElOkf+lj60YJWokTywA2XifP837Pd8lpSK8h9XCf588Alx+xYYztkFWvyRm4OIp11GvFKK+lqmzhf6lODpoF5/Eka9UGTjhj34BRb7VF+sLcWTLgnx/XnnrtcDJnLWzfbDhvQxQ82hhWBjKdLGhV4cqkLJKAxToPbdt6jKK7wAEoWDf1Qxnt4FK4hgEd9Yw8DC6vjmeGXaJle/q1wx3uqcUtM1+5gAMJN5deLP3z8ms6qfWvHvuWmDZMlpgwAi+pCEKuH9pSiwzR9Yxz3I88b2MzxvPvy4UJmxMsWoEZ80CWTxAdow2TFK1a5uQahWbksLiZ8yN2qacaTrdTXrPVq/5quE5o6QsOeuPkBxqMmrsoI01itgPH2e8txHZJuPRpRJSXkFnnWnolj5sZRW3QaB0D2421GK/UPA8RS/EKNA9Ya8O79nsoV2GbvMKpStwQQJkCenn6sSywcBhE="
